//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagementDB_DataEntities : DbContext
    {
        public HotelManagementDB_DataEntities()
            : base("name=HotelManagementDB_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adult> Adults { get; set; }
        public virtual DbSet<BeddingType> BeddingTypes { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<OrderFood> OrderFoods { get; set; }
        public virtual DbSet<Reservasion> Reservasions { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomQuantity> RoomQuantities { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
    }


    public class GeustFoodOrder
    {
        public IEnumerable<Food> Foods { get; set; }
        public IEnumerable<OrderFood> OrderFoods { get; set; }
        public IEnumerable<Guest> Guests { get; set; }
    }
}
