//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderFood
    {
        public int OrderId { get; set; }
        [Required]
        [Display(Name = "Guest Name")]
        public Nullable<int> GuestId { get; set; }
        [Required]
        [Display(Name = "Food Name")]

        public Nullable<int> FoodId { get; set; }
        [Required]
        [Display(Name = "Item Quantity")]
        public int Quntity { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
