//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservasion
    {
        public int ReservasionId { get; set; }
        [Required]
        [Display(Name = "Guest Name")]        
        public Nullable<int> GuestId { get; set; }
        [Required]
        [Display(Name = "Room Name")]
        public Nullable<int> RoomId { get; set; }
        [Required]
        [Display(Name = "Number of Adult")]
        public Nullable<int> AdultId { get; set; }
        [Required]
        [Display(Name = "Number of Child")]
        public Nullable<int> ChildId { get; set; }
        [Required]
        [Display(Name = "Room Quantity")]
        public Nullable<int> RoomQuantityId { get; set; }
        [Required]
        [Display(Name = "Arrival Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        [Required]
        [Display(Name = "Departure Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DepartureDate { get; set; }
    
        public virtual Adult Adult { get; set; }
        public virtual Child Child { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
        public virtual RoomQuantity RoomQuantity { get; set; }
    }
}
