//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Reservasions = new HashSet<Reservasion>();
        }
    
        public int RoomId { get; set; }
        [Required]
        [Display(Name = "Room Name")]
        [StringLength(50)]
        public string RoomTypeName { get; set; }
        [Required]
        [Display(Name = "Room Quality")]
        public Nullable<int> RoomTypeId { get; set; }
        [Required]
        [Display(Name = "Bedding Type")]
        public Nullable<int> BeddingTypeId { get; set; }

        [Display(Name = "Room Image")]
        [DataType(DataType.Upload)]
        public string ImageUrl { get; set; }
        [Required]
        [Display(Name = "Rate of Room")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Price { get; set; }
    
        public virtual BeddingType BeddingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservasion> Reservasions { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
